### ISSUE TITLE
[Bug]: Bundled retro_wave.glsl fails with sdBox redefinition

### ISSUE THREAD

**Issue by reuben-geonet** [1ay1/neowall#82]
### Bug Description

The bundled `retro_wave.glsl` fails to compile on NeoWall v0.7.0 because `sdBox(vec3, vec3)` is defined both by the shader and the automatically injected standard library. NeoWall exits during startup.

### Steps to Reproduce

1. Configure the bundled shader as shown below.
2. Run `neowall -f -v` on Sway with Intel graphics.
3. Observe the shader compilation error and process exit.

### Expected Behavior

The bundled shader compiles and runs as the wallpaper.

### Actual Behavior

Shader compilation fails with `function sdBox redefined`, configuration application fails, and NeoWall exits. In daemon mode, the terminal initially prints `Running as daemon...`, but a subsequent `neowall reload` reports that no daemon is running.

### Logs

```text
ERROR: fragment shader compilation failed: 0:86(7): error: function `sdBox' redefined
ERROR: Failed to compile multipass shader: retro_wave.glsl
ERROR: Failed to apply default config to output 'DP-5'
ERROR: Configuration was valid, but one or more resources failed to apply
ERROR: No built-in fallback will be applied after an application failure
ERROR: Failed to load configuration
```

### Staticwall Version

`neowall --version` reports `NeoWall v0.7.0`. The template's `staticwall` command appears stale.

### Wayland Compositor

Sway

### Compositor Version

sway version 1.11

### Operating System

Fedora

### OS Version

Fedora Linux 44, x86_64

### Configuration File

```text
default {
  shader retro_wave.glsl
  shader_speed 0.8
}
```

### Installation Method

Other — v0.7.0 built from source and installed as a local RPM (`neowall-0.7.0-1.local1.x86_64`) with corrected Fedora dependency metadata.

### Additional Context

Intel Alder Lake-P integrated graphics, Mesa 26.1.8; two outputs detected during the failing startup.

The shader defines `sdBox(vec3, vec3)` in [retro_wave.glsl](https://github.com/1ay1/neowall/blob/v0.7.0/examples/shaders/retro_wave.glsl#L86). The same signature exists in [shader_stdlib.h](https://github.com/1ay1/neowall/blob/v0.7.0/include/neowall/shader/shader_stdlib.h#L186), which [wrap_pass_source](https://github.com/1ay1/neowall/blob/v0.7.0/src/shader/shader_multipass.c#L555) injects unconditionally.

Please prevent helper-name collisions and add compilation checks for the bundled shaders.

### Pre-submission Checklist

- [x] Searched existing issues for duplicates.
- [x] Included the NeoWall version.
- [x] Included relevant logs from `neowall -f -v`.
- [x] Included the configuration that triggered the failure.

**Comment by 1ay1** [comment]
Thanks for the detailed report, the log made this easy to find.

You hit a real bug and it was worse than just that one shader. The std-lib header claimed it had no unprefixed aliases, but it was actually shipping 15 of them — `sdBox`, `pulse`, `beat`, `spectrum`, `sdSphere` and friends. Those are exactly the names a raymarching shader defines for itself, and in GLSL a second definition is a hard error rather than a shadow. So any Shadertoy shader defining one of those would fail, which breaks the whole "paste an unmodified Shadertoy shader in" promise. Been there since v0.5.0, you just happened to hit it via the Fedora package.

Fixed in 25e0e5f:

- Everything in the std-lib is now `nw*` prefixed and internally only calls `nw*` names.
- The friendly short names are emitted at injection time only if your shader does not already define them. Define `sdBox` and you get yours, `nwSdBox` is still there if you want it.
- They are forwarding functions, not `#define`s — a macro would have rewritten your own definition and caused the same error again.

Also added a test that parses the std-lib header itself and fails CI if anyone adds an unprefixed helper without registering it, so this specific class of bug cannot come back.

retro_wave.glsl now compiles and runs at 59.2 FPS with 0 errors here. Please pull latest and confirm on your Sway/Intel setup.
